<?php
$order = $block->getOrder();
?>

<div class="checkout-success">
     <?php if ($order->getIncrementId()):?>
               <?php if ($block->getCustomerId()):?>
            <p><?= $block->escapeHtml(
                __(
                    'Your order number is: %1.',
                    sprintf(
                        '<a href="%s" class="order-number"><strong>%s</strong></a>',
                        $block->escapeUrl($block->getViewOrderUrl()),
                        $order->getIncrementId()
                    )
                ),
                ['a', 'strong']
            ) ?></p>
        <?php  else:?>
            <p><?= $block->escapeHtml(
                __(
                    'Your order # is: <span>%1</span>.',
                    $order->getIncrementId()
                ),
                ['span']
            ) ?></p>
        <?php endif;?>
            <p><?= $block->escapeHtml(
                __(
                    'We\'ll email you an order confirmation with details and tracking info.'
                )
            ) ?></p>
    <?php endif;?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
               href="<?= $block->escapeUrl($block->getContinueUrl()) ?>">
               <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>