<input type="hidden" name="<?php echo $this->getNamePrefix() ?>" value="" />
<ul class="checkboxes">
    <?php foreach ($this->getValues() as $name => $label): ?>
        <li>
            <input type="checkbox" value="<?php echo $name?>" name="<?php echo $this->getNamePrefix() ?>[]" id="<?php echo $this->getHtmlId() . '_' . $name ?>"<?php echo ($this->getIsChecked($name) ? ' checked="checked"' : '') ?>/>
                <label for="<?php echo $this->getHtmlId() . '_' . $name ?>">
                <?php echo $label ?>
            </label>
            <?php if ($name == 'billetera') { ?>
                <div class="tooltip">
                    <span class="help">
                        <span></span>
                    </span>
                    <div class="tooltip-content">
                        Tus clientes pueden pagar con Yape, Plin y las principales billeteras móviles del país.
                    </div>
                </div>
            <?php } ?>
            <?php if ($name == 'cuotealo') { ?>
                <div class="tooltip">
                    <span class="help">
                        <span></span>
                    </span>
                    <div class="tooltip-content">
                        Paga en cuotas y sin tarjetas de crédito con Cuotéalo
                    </div>
                </div>
            <?php } ?>
        </li>
    <?php endforeach;?>
</ul>
<span id="errorpaymentmethods" class="form-text text-muted" style="display: block; color: red; font-size: 1rem !important;"></span>