<input id="<?php echo $this->getHtmlId() ?>"
        name="<?php echo $this->getNamePrefix() ?>"
        data-ui-id="text-groups-culqi-fields-timexp-value"
        value="<?php echo $this->getValue() ?>"
        class=" input-text admin__control-text number-only" type="text" >
<span id="errortimeexp" class="form-text text-muted" style="display: block; color: red; font-size: 1rem !important;"></span>

<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function() {
    // Select the input field(s) you want to apply this to
    const inputField = document.querySelector('input.number-only');
    
    inputField.addEventListener('input', function() {
        // Allow only numeric input
        this.value = this.value.replace(/[^0-9]/g, '');
    
        // Limit the input to a maximum of 3 digits
        if (this.value.length > 3) {
        this.value = this.value.slice(0, 3);
        }
    });
});      
</script>