<style>
    .admin__scope-old input[type=number] {
        width: 100% !important
    }

    .modal-inner-wrap {
        max-width: 1150px;
    }

    .customcheckout li {
        list-style: none;
    }

    .customcheckout hr {
        border: 1px solid #e7e9ec;
        margin: 14px 0;
    }

    .customcheckout input[type="text"],
    .customcheckout input[type="email"],
    .customcheckout input[type="url"],
    .customcheckout input[type="tel"] {
        color: #3e4b61;
        width: 100%;
        border: 1px solid transparent;
        height: 40px;
        display: block;
        padding: 0.375rem 16px;
        font-size: 14px;
        transition: border-color 0.15s ease-in-out;
        box-sizing: border-box;
        line-height: 1.5;
        border-radius: 4px !important;
        font-family: "Lexend Deca", sans-serif !important;
        background-color: #F9F9FA;
    }

    .customcheckout input[type="text"].pointer-none,
    .customcheckout input[type="email"].pointer-none,
    .customcheckout input[type="url"].pointer-none,
    .customcheckout input[type="tel"].pointer-none {
        pointer-events: none;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    .customcheckout input[type="text"].invalid,
    .customcheckout input[type="email"].invalid,
    .customcheckout input[type="url"].invalid,
    .customcheckout input[type="tel"].invalid {
        border-color: #f58585;
    }

    .customcheckout input[type="text"].valid,
    .customcheckout input[type="email"].valid,
    .customcheckout input[type="url"].valid,
    .customcheckout input[type="tel"].valid {
        border-color: #00A19B;
    }


    .customcheckout input[type="text"]::-webkit-input-placeholder,
    .customcheckout input[type="email"]::-webkit-input-placeholder,
    .customcheckout input[type="url"]::-webkit-input-placeholder,
    .customcheckout input[type="tel"]::-webkit-input-placeholder {
        color: #b1b8c1;
    }

    .customcheckout input[type="text"]:-ms-input-placeholder,
    .customcheckout input[type="email"]:-ms-input-placeholder,
    .customcheckout input[type="url"]:-ms-input-placeholder,
    .customcheckout input[type="tel"]:-ms-input-placeholder {
        color: #b1b8c1;
    }

    .customcheckout input[type="text"]::-ms-input-placeholder,
    .customcheckout input[type="email"]::-ms-input-placeholder,
    .customcheckout input[type="url"]::-ms-input-placeholder,
    .customcheckout input[type="tel"]::-ms-input-placeholder {
        color: #b1b8c1;
    }

    .customcheckout input[type="text"]::placeholder,
    .customcheckout input[type="email"]::placeholder,
    .customcheckout input[type="url"]::placeholder,
    .customcheckout input[type="tel"]::placeholder {
        color: #b1b8c1 !important;
    }

    .customcheckout input[type="text"]:focus,
    .customcheckout input[type="email"]:focus,
    .customcheckout input[type="url"]:focus,
    .customcheckout input[type="tel"]:focus {
        outline: none;
        -webkit-transition: all 0.15s ease-in-out;
        transition: all 0.15s ease-in-out;
        border-color: #3cb4e5;
    }

    .customcheckout input[type="radio"] {
        -webkit-appearance: none;
        width: 15px;
        height: 15px;
        border: 3px solid #b1b8c1;
        border-radius: 50%;
        position: relative;
        cursor: pointer;
    }

    .customcheckout input[type="radio"]:checked {
        border: 6px solid #3cb4e5;
    }

    .customcheckout input[type="radio"]:focus {
        outline: none !important;
    }

    .customcheckout select {
        color: #3e4b61;
        width: 100%;
        border: 1px solid transparent;
        height: 40px;
        display: block;
        padding: 0.375rem 0.75rem;
        font-size: 14px;
        -webkit-transition: border-color 0.15s ease-in-out;
        transition: border-color 0.15s ease-in-out;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
        line-height: 1.5;
        border-radius: 4px !important;
        font-family: "Lexend Deca", sans-serif !important;
        background-color: #F9F9FA !important;
        cursor: pointer;
        min-width: 100px;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        padding: 0.375rem 1.5rem 0.375rem 0.75rem;
        pointer-events: none;
    }

    .customcheckout .btn,
    .modal-footer .btn-close-checkout-preview,
    .modal-footer .btn-save-checkout-preview {
        display: -webkit-inline-box;
        display: -ms-inline-flexbox;
        display: inline-flex;
        padding: 10px 36px;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        text-align: center;
        border: 0;
        text-decoration: none;
        text-transform: initial;
        letter-spacing: 0;
        -webkit-transition: all 0.15s ease-in-out;
        transition: all 0.15s ease-in-out;
        cursor: pointer;
        font-weight: 600;
        font-family: "Lexend Deca", sans-serif !important;
        font-size: 14px;
        height: 40px;
        color: #888888;
        border-radius: 4px;
    }

    .customcheckout .btn-disabled,
    .modal-footer .btn-save-checkout-preview.disabled {
        background-color: #d4d8dd;
    }

    .customcheckout .btn-without-line,
    .modal-footer .btn-close-checkout-preview {
        background: none;
    }

    .customcheckout .btn-save,
    .modal-footer .btn-save-checkout-preview {
        background-color: #00a19b;
        color: #ffffff;
    }


    .customcheckout .btn-save.disabled,
    .modal-footer .btn-save-checkout-preview.disabled {
        cursor: default;
        background-color: #d4d8dd;
        color: #b1b8c1;
    }

    .customcheckout .overlay {
        width: 0;
        height: 0;
        position: fixed;
        top: 0;
        left: 0;
        visibility: hidden;
        background: rgba(0, 0, 0, 0.6);
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        z-index: 999;
    }

    .customcheckout .overlay.active {
        visibility: visible;
        width: 100%;
        height: 100vh;
    }

    .customcheckout .containerpopup {
        max-width: 1074px;
        min-height: 730px;
        width: 100%;
        background: #ffffff;
        border-radius: 4px;
        overflow: hidden;
    }

    .customcheckout .custom-checkout {
        padding: 20px 0 34px 0;
    }

    .customcheckout .custom-checkout__header {
        border-bottom: 1px solid #e7e9ec;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -ms-flex-pack: justify;
        justify-content: space-between;
        padding: 0 20px 20px;
    }

    .customcheckout .custom-checkout__header-title {
        font-family: "Lexend Deca", sans-serif !important;
        font-weight: 600;
        font-size: 18px;
        line-height: 28px;
    }

    .customcheckout .custom-checkout__header-close {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        cursor: pointer;
        -webkit-transition: 0.17s all ease-in;
        transition: 0.17s all ease-in;
    }

    .customcheckout .custom-checkout__header-close:hover {
        -webkit-transform: scale(1.1);
        transform: scale(1.1);
    }

    .customcheckout .custom-checkout__footer {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: end;
        -ms-flex-pack: end;
        justify-content: flex-end;
        padding: 0 60px;
    }

    .customcheckout .custom-checkout__footer .btn {
        padding: 6px 12px;
    }

    .customcheckout .custom-checkout__footer .btn:first-child {
        margin-right: 10px;
    }

    .customcheckout .custom-checkout__footer .btn-without-line:hover {
        color: #000000;
    }

    .customcheckout .custom-checkout__body {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        width: 100%;
        min-height: 545px;
        padding: 24px 25px;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }

    .customcheckout .custom-checkout__body .content {
        width: 100%;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -ms-flex-pack: justify;
        justify-content: space-between;
    }

    .customcheckout .custom-checkout__body .preview {
        max-width: 576px;
        width: 100%;
        pointer-events: none;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    .customcheckout .custom-checkout__body .preview-checkout {
        border-radius: 8px;
        overflow: hidden;
        width: 100%;
        min-height: 545px;
        -webkit-box-shadow: 0px 8px 12px rgba(9, 30, 66, 0.15), 0px 0px 1px rgba(9, 30, 66, 0.31);
        box-shadow: 0px 8px 12px rgba(9, 30, 66, 0.15), 0px 0px 1px rgba(9, 30, 66, 0.31);
    }

    .customcheckout .custom-checkout__body .preview-checkout__banner {
        width: 100%;
        background-color: #000000;
        height: 52px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        padding: 16px;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: start;
        -ms-flex-pack: start;
        justify-content: flex-start;
    }

    .customcheckout .custom-checkout__body .preview-checkout__banner .banner-logo {
        background: #ffffff;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        place-content: center;
        width: 56px;
        height: 56px;
        border-radius: 8px;
        -webkit-transform: translateY(20px);
        transform: translateY(20px);
        padding: 4px;
    }

    .customcheckout .custom-checkout__body .preview-checkout__banner .banner-logo img {
        width: 48px;
        height: 48px;
        padding: 4px;
        border-radius: 4px;
        -webkit-box-shadow: 0px 3px 5px rgba(9, 30, 66, 0.2), 0px 0px 1px rgba(9, 30, 66, 0.31);
        box-shadow: 0px 3px 5px rgba(9, 30, 66, 0.2), 0px 0px 1px rgba(9, 30, 66, 0.31);
        -o-object-fit: contain;
        object-fit: contain;
    }

    .customcheckout .custom-checkout__body .preview-checkout__banner .banner-title {
        color: #ffffff;
        font-family: "Lexend Deca", sans-serif !important;
        font-weight: 600;
        font-size: 18px;
        line-height: 28px;
        margin-left: 16px;
    }

    .customcheckout .custom-checkout__body .preview-checkout__amount {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: end;
        -ms-flex-pack: end;
        justify-content: flex-end;
        padding: 6px 16px;
        border-bottom: 1px solid #e7e9ec;
    }

    .customcheckout .custom-checkout__body .preview-checkout__amount-contain {
        font-family: "Lexend Deca", sans-serif !important;
        font-weight: normal;
        font-size: 16px;
        line-height: 17px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        color: #00a19b;
    }

    .customcheckout .custom-checkout__body .preview-checkout__amount-contain svg {
        margin-left: 9px;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container {
        width: 100%;
        height: 100%;
        display: -ms-grid;
        display: grid;
        grid-template-columns: 201px auto;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-menu {
        width: 100%;
        height: 457px;
        border-right: 1px solid #e7e9ec;
        padding: 16px 11px 12px 8px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        -webkit-box-pack: justify;
        -ms-flex-pack: justify;
        justify-content: space-between;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-menu ul {
        list-style-type: none;
        padding: 0;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-menu ul li {
        font-family: "Lexend Deca", sans-serif !important;
        color: #1F263E;
        font-size: 12px;
        font-weight: 400;
        line-height: 20px;
        list-style: none;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        position: relative;
        padding-left: 8px;
        margin-bottom: 16px;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-menu ul li.menu-color {
        color: #00a19b;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-menu ul li .barra {
        display: block;
        height: 20px;
        width: 2px;
        border-radius: 4px;
        position: absolute;
        left: 0;
        background: #00a19b;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-menu ul li img,
    .customcheckout .custom-checkout__body .preview-checkout__container-menu ul li svg {
        margin-right: 10px;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-menu-image {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        margin: 0 auto;
        max-width: 117px;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-content {
        padding: 24px 20px;
        position: relative;
        width: 100%;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-content .form-info {
        font-family: "Lexend Deca", sans-serif !important;
        font-style: normal;
        font-weight: normal;
        font-size: 12px;
        line-height: 13px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        position: relative;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        margin: 0 auto;
        color: #1F263E;
    }

    .customcheckout .custom-checkout__body .preview-checkout__container-content .form-info svg {
        width: auto !important;
    }

    .customcheckout .custom-checkout__body .personalize {
        font-family: "Lexend Deca", sans-serif !important;
        height: 545px;
        max-width: 400px;
        width: 100%;
        padding: 10px 10px 10px 1px;
        overflow-y: auto;
    }

    .customcheckout .custom-checkout__body .personalize::-webkit-scrollbar {
        width: 16px;
    }

    .customcheckout .custom-checkout__body .personalize::-webkit-scrollbar-track {
        background: #f9f9fa;
    }

    .customcheckout .custom-checkout__body .personalize::-webkit-scrollbar-thumb {
        background-color: #d4d8dd;
        border-radius: 20px;
        border: 3px solid #f9f9fa;
    }

    .customcheckout .custom-checkout__body .personalize .title {
        font-weight: bold;
        font-size: 16px;
        line-height: 24px;
        color: #1f263e;
    }

    .customcheckout .custom-checkout__body .personalize .subtitle {
        font-weight: 600;
        font-size: 12px;
        line-height: 16px;
        color: #3e4b61;
        margin-bottom: 8px;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo {
        margin-bottom: 20px;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content {
        margin-top: 35px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo {
        width: 220px;
        display: -ms-grid;
        display: grid;
        -ms-grid-columns: 1fr 1fr 1fr;
        grid-template-columns: 1fr 1fr 1fr;
        grid-column-gap: 8px;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo__item {
        border: 0.5px solid #e7e9ec;
        width: 68px;
        height: 68px;
        border-radius: 4px;
        position: relative;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo__item .check,
    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo__item .errorlogo {
        z-index: 1;
        position: absolute;
        left: 50%;
        -webkit-transform: translate(-50%, -8px);
        transform: translate(-50%, -8px);
        width: 15px;
        height: 15px;
        border-radius: 50%;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo__item .check svg,
    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo__item .errorlogo svg {
        width: 10px !important;
        height: 10px !important;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo__item .check {
        background-color: #499636;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo__item .errorlogo {
        background-color: #d20808;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo__item .image {
        width: 100%;
        height: 100%;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .iso-logo__item .image img {
        width: 48px;
        height: 48px;
        padding: 4px;
        border-radius: 3px;
        -webkit-box-shadow: 0px 3px 5px rgba(9, 30, 66, 0.2), 0px 0px 1px rgba(9, 30, 66, 0.31);
        box-shadow: 0px 3px 5px rgba(9, 30, 66, 0.2), 0px 0px 1px rgba(9, 30, 66, 0.31);
        -o-object-fit: contain;
        object-fit: contain;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .detail-logo {
        margin-left: 11px;
        padding-left: 16px;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .detail-logo__list {
        font-family: "Lexend Deca", sans-serif !important;
        font-style: normal;
        font-weight: normal;
        font-size: 12px;
        line-height: 16px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        color: #677487;
        margin-bottom: 4px;
        position: relative;
    }

    .customcheckout .custom-checkout__body .personalize-logotipo__content .detail-logo__list svg {
        position: absolute;
        left: -16px;
        top: 50%;
        -webkit-transform: translateY(-50%);
        transform: translateY(-50%);
    }

    .customcheckout .custom-checkout__body .personalize-url .form__group label {
        margin-top: 4px;
        font-size: 11.24px;
        line-height: 16px;
        color: #677487;
    }

    .customcheckout .custom-checkout__body .personalize-color .paragraph {
        font-size: 14.22px;
        line-height: 20px;
        color: #3e4b61;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item {
        margin-bottom: 20px;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .action-visible {
        font-weight: 600;
        font-size: 12px;
        line-height: 16px;
        color: #3cb4e5;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        cursor: pointer;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .action-visible svg {
        margin-right: 6px;
        -webkit-transition: 0.5s all ease;
        transition: 0.5s all ease;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .action-visible svg.rotate {
        -webkit-transform: rotate(180deg);
        transform: rotate(180deg);
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .action-container {
        margin-top: 19px;
        height: 0;
        -webkit-transition: 0.5s all ease-in;
        transition: 0.5s all ease-in;
        visibility: hidden;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .action-container .color-palette,
    .customcheckout .custom-checkout__body .personalize-color__content-item .action-container .subtitle {
        display: none;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .action-container.active {
        height: auto;
        visibility: visible;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .action-container.active .color-palette,
    .customcheckout .custom-checkout__body .personalize-color__content-item .action-container.active .subtitle {
        display: -ms-grid;
        display: grid;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .color-palette {
        display: -ms-grid;
        display: grid;
        -ms-grid-columns: (minmax(84px, 84px)) [ auto-fill];
        grid-template-columns: repeat(auto-fill, minmax(84px, 84px));
        grid-column-gap: 12px;
        -ms-grid-rows: (minmax(42px, 1fr)) [ auto-fill];
        grid-template-rows: repeat(auto-fill, minmax(42px, 1fr));
        grid-row-gap: 12px;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .color-palette__item {
        -webkit-box-shadow: 0px 1px 3px rgba(9, 30, 66, 0.2), 0px 0px 1px rgba(9, 30, 66, 0.31);
        box-shadow: 0px 1px 3px rgba(9, 30, 66, 0.2), 0px 0px 1px rgba(9, 30, 66, 0.31);
        border-radius: 4px;
        padding: 6px 12px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -ms-flex-pack: justify;
        justify-content: space-between;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .color-palette__item label {
        width: 30px;
        height: 30px;
        position: relative;
        cursor: pointer;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .color-palette__item label .color-container {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .color-palette__item label .color-container__left {
        width: 15px;
        height: 28px;
        border-radius: 100px 0 0 100px;
    }

    .customcheckout .custom-checkout__body .personalize-color__content-item .color-palette__item label .color-container__right {
        width: 15px;
        height: 28px;
        border-radius: 0 100px 100px 0;
    }

    .customcheckout .form {
        display: -ms-grid;
        display: grid;
        width: 100%;
        max-width: 312px;
        -ms-grid-columns: 1fr 1fr;
        grid-template-columns: 1fr 1fr;
        -ms-grid-rows: auto;
        grid-template-rows: auto;
        background-color: inherit;
    }

    .customcheckout .form__row label {
        font-family: "Lexend Deca", sans-serif !important;
        font-weight: bold !important;
        margin-bottom: 4px;
        line-height: 16px;
        color: #3E4B61;
        font-size: 12px;
        letter-spacing: normal;
    }

    .customcheckout .form__group {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        margin-bottom: 20px;
        position: relative;
    }

    .customcheckout .form__group-input {
        position: relative;
    }

    .customcheckout .form__group-input .opacity,
    .customcheckout .form__group .opacity {
        opacity: 0.5 !important;
    }

    .customcheckout .form__group__select {
        position: relative;
        pointer-events: none;
    }

    .customcheckout .form__group__select::before {
        content: url("https://culqi-static-files.s3.amazonaws.com/v4/v4-checkout/icons/arrow_down.svg");
        position: absolute;
        top: 50%;
        -webkit-transform: translateY(-50%);
        transform: translateY(-50%);
        bottom: 0;
        right: 15px;
        pointer-events: none;
        -webkit-transition: 0.5s all;
        transition: 0.5s all;
    }

    .customcheckout .form__row {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        width: 100%;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
    }

    .customcheckout .form__row__col {
        -ms-flex-preferred-size: 0;
        flex-basis: 0;
        -webkit-box-flex: 1;
        -ms-flex-positive: 1;
        flex-grow: 1;
        max-width: 100%;
    }

    .customcheckout .form__row__col .btn {
        background-color: #00A19B;
        color: #FFFFFF;

    }

    .customcheckout .form__row__col.right {
        padding-left: 10px;
    }

    .customcheckout .form__row__col.left {
        padding-right: 10px;
    }

    .customcheckout .form .dobble {
        -ms-grid-column: 1;
        -ms-grid-column-span: 2;
        grid-column: 1 / span 2;
    }

    .customcheckout .form .dobble .form__row__col {
        padding-right: 0;
        padding-left: 0;
    }

    .customcheckout .form .brand {
        height: 20px;
        width: 30px;
        border-radius: 2px;
        position: absolute;
        top: 50%;
        right: 20px;
        -webkit-transform: translateY(-50%);
        transform: translateY(-50%);
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        background-size: contain;
        background-image: url(https://culqi-static-files.s3.amazonaws.com/v3/v3-checkout/logos/red-service/visa.png);
    }

    @media screen and (max-width: 782px) {
        .customcheckout {
            display: none;
        }
    }

    .can-toggle label .can-toggle__switch:before {
        content: none !important;
    }

    #contact-popup {
        position: fixed;
        top: 0px;
        left: 0px;
        height: 100%;
        width: 100%;
        color: #676767;
        z-index: 999;
        background: rgba(0, 0, 0, 0.7);
    }

    .contact-form {
        width: 370px;
        margin: 0px;
        background-color: white;
        font-family: Arial;
        position: relative;
        left: 50%;
        top: 60%;
        margin-left: -210px;
        margin-top: -255px;
        box-shadow: 1px 1px 5px #444444;
        padding: 20px 40px 40px 40px;
    }

    #contact-icon {
        padding: 10px 5px 5px 12px;
        width: 58px;
        color: white;
        box-shadow: 1px 1px 5px grey;
        border-radius: 3px;
        cursor: pointer;
        margin: 60px auto;
    }

    .info {
        color: #d30a0a;
        letter-spacing: 2px;
        padding-left: 5px;
    }

    #send {
        background-color: #29a19b;
        border: 1px solid #29a19b;
        color: white;
        width: 100%;
        padding: 10px;
        cursor: pointer;
    }

    #contact-popup h1 {
        font-weight: normal;
        text-align: center;
        margin: 10px 0px 20px 0px;
        font-size: 20px;
        text-align: center;
    }

    #contact-popup p {
        font-size: 14px;
        text-align: center;
    }

    #contact-popup div {
        text-align: center;
    }

    .modal-inner-wrap {
        width: 70% !important;
    }

    @media screen and (max-width: 1100px) {
        .modal-inner-wrap {
            transform: scale(0.7) !important;
            width: auto !important;
        }
    }

    .accordion .config .note {
        font-size: 10px !important;
    }

    .accordion .config .value {
        width: 47% !important;
    }

    div.image {
        margin: 0 !important;
    }
</style>

<!-- <div data-mage-init='{"myjs": {}}'>
    <a href="#" id="click-me">Click Me</a>
</div> -->


<div class="form-group customcheckout">
    <div class="col-lg-8">
        <div class="">
            <div class="container" style="justify-content: center; margin: auto;">
                <input value="Personalizar" type="button" class="btn btn-save" id="open-modal">
            </div>
        </div>
    </div>
</div>



<div class="customcheckout overlay " id="popup-modal">
    <div class="container containerpopup">
        <div class="custom-checkout">
            <!-- <div class="custom-checkout__header">
                                            <div class="custom-checkout__header-title">Personalización</div>
                                            <div class="custom-checkout__header-close" id="btn-close">
                                                <img src="https://culqi-static-files.s3.amazonaws.com/v4/v4-checkout/icons/close-black.svg" alt="close">
                                            </div>
                                        </div> -->
            <div class="custom-checkout__body">
                <div class="content">
                    <div class="preview">
                        <div class="preview-checkout">
                            <div class="preview-checkout__banner" id="palette-left" style="background: rgb(180, 5, 147);">
                                <div class="banner-logo">
                                    <img id="logo" src="https://culqi-static-files.s3.amazonaws.com/v3/v3-checkout/brand.svg" alt="logo">
                                </div>
                                <div class="banner-title">
                                    <?php echo $this->getStoreName() ?>
                                </div>
                            </div>
                            <div class="preview-checkout__amount">
                                <div class="preview-checkout__amount-contain">
                                    <span id="palette-right" name="color" style="color: rgb(211, 44, 181);">S/ 350.00</span>
                                    <svg style="width: 20px!important; height: 20px!important" width="22" height="22" viewBox="0 0 43 43" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" id="palette-right" name="svg" clip-rule="evenodd" d="M2.39404 14.3924C2.39404 9.80605 6.11198 6.0881 10.6983 6.0881H31.6775C36.2638 6.0881 39.9817 9.80605 39.9817 14.3924V23.1337C39.9817 23.8578 39.3947 24.4449 38.6705 24.4449C37.9464 24.4449 37.3593 23.8578 37.3593 23.1337V14.3924C37.3593 11.2544 34.8155 8.7105 31.6775 8.7105H10.6983C7.56029 8.7105 5.01644 11.2544 5.01644 14.3924V28.3785C5.01644 31.5165 7.56029 34.0603 10.6983 34.0603H22.9361C23.6603 34.0603 24.2473 34.6474 24.2473 35.3715C24.2473 36.0957 23.6603 36.6827 22.9361 36.6827H10.6983C6.11198 36.6827 2.39404 32.9648 2.39404 28.3785V14.3924Z" fill="#00A19B" />
                                        <path id="palette-right" name="svg" d="M12.4462 14.3924C12.4462 13.4268 11.6635 12.6441 10.698 12.6441C9.73243 12.6441 8.94971 13.4268 8.94971 14.3924C8.94971 15.3579 9.73243 16.1406 10.698 16.1406C11.6635 16.1406 12.4462 15.3579 12.4462 14.3924Z" fill="#00A19B" />
                                        <path fill-rule="evenodd" id="palette-right" name="svg" clip-rule="evenodd" d="M21.1876 23.5707C19.9807 23.5707 19.0023 22.5923 19.0023 21.3854C19.0023 20.1785 19.9807 19.2001 21.1876 19.2001C22.3945 19.2001 23.3729 20.1785 23.3729 21.3854C23.3729 22.5923 22.3945 23.5707 21.1876 23.5707ZM16.3799 21.3854C16.3799 24.0407 18.5324 26.1931 21.1876 26.1931C23.8428 26.1931 25.9953 24.0407 25.9953 21.3854C25.9953 18.7302 23.8428 16.5777 21.1876 16.5777C18.5324 16.5777 16.3799 18.7302 16.3799 21.3854Z" fill="#00A19B" />
                                        <path fill-rule="evenodd" id="palette-right" name="svg" clip-rule="evenodd" d="M39.5339 27.3917C40.0789 27.8686 40.1341 28.6969 39.6572 29.2419L34.6399 34.976C33.5617 36.2082 31.7047 36.3732 30.4262 35.3504L27.3618 32.8989C26.7963 32.4465 26.7046 31.6214 27.157 31.0559C27.6094 30.4904 28.4345 30.3988 29 30.8511L32.0644 33.3026C32.247 33.4488 32.5123 33.4252 32.6663 33.2492L37.6837 27.515C38.1605 26.9701 38.9889 26.9148 39.5339 27.3917Z" fill="#00A19B" />
                                    </svg>
                                </div>
                            </div>
                            <div class="preview-checkout__container">
                                <div class="preview-checkout__container-menu">
                                    <ul>
                                        <li class="menu-color" id="palette-right" name="color">
                                            <span class="barra" id="palette-right" name="bg"></span>
                                            <svg style="width: 20px!important; height: 20px!important" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <g clip-path="url(#clip0_478_2813)">
                                                    <path fill-rule="evenodd" clip-rule="evenodd" id="palette-right" name="svg" d="M3.94475 4.5H16.0552C17.0276 4.5 17.9116 5.38 18 6.436V13.564C18 14.62 17.116 15.5 16.0552 15.5H3.94475C2.88398 15.5 2 14.62 2 13.564V6.436C2 5.38 2.88398 4.5 3.94475 4.5ZM16.0552 5.644H3.94475C3.50276 5.644 3.14917 5.996 3.14917 6.436V6.964H16.8508V6.436C16.8508 5.996 16.4972 5.644 16.0552 5.644ZM3.94475 14.268H16.0552C16.4088 14.268 16.7624 13.916 16.7624 13.564V8.108H3.14917V13.476C3.14917 13.916 3.50276 14.268 3.94475 14.268ZM4.20989 11.892H6.68503V13.036H4.20989V11.892Z" fill="#00A19B"></path>
                                                </g>
                                                <defs>
                                                    <clipPath id="clip0_478_2813">
                                                        <rect width="16" height="11" fill="white" transform="translate(2 4.5)"></rect>
                                                    </clipPath>
                                                </defs>
                                            </svg>
                                            Tarjeta débito/crédito
                                        </li>
                                        <li>
                                            <img src="https://culqi-static-files.s3.amazonaws.com/v4/v4-checkout/icons/yape.svg" alt="icon">
                                            Yape
                                        </li>
                                        <li>
                                            <img src="https://culqi-static-files.s3.amazonaws.com/v4/v4-checkout/icons/banca-movil.svg" alt="icon">

                                            Billeteras móviles
                                        </li>
                                        <li>
                                            <img src="https://culqi-static-files.s3.amazonaws.com/v4/v4-checkout/icons/online-banking.svg" alt="icon">
                                            Banca móvil o internet
                                        </li>
                                        <li>
                                            <img src="https://culqi-static-files.s3.amazonaws.com/v4/v4-checkout/icons/agents.svg" alt="icon">
                                            Agentes y bodegas
                                        </li>
                                        <li>
                                            <img src="https://culqi-static-files.s3.amazonaws.com/v4/v4-checkout/icons/bcp.svg" alt="icon">
                                            Cuotéalo BCP
                                        </li>
                                    </ul>
                                    <div class="preview-checkout__container-menu-image">
                                        <img src="https://culqi-static-files.s3.amazonaws.com/v3/v3-checkout/logos/culqi-black.svg" alt="Culqi logo">
                                    </div>
                                </div>
                                <div class="preview-checkout__container-content">
                                    <span class="form-info">
                                        <svg width="15" height="13" viewBox="0 0 29 29" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <circle cx="14.0867" cy="8.22975" r="1.16551" fill="#00A19B" />
                                            <path fill-rule="evenodd" id="palette-right" name="svg" clip-rule="evenodd" d="M14.0868 3.27637C8.13268 3.27637 3.30588 8.10317 3.30588 14.0573C3.30588 20.0115 8.13268 24.8383 14.0868 24.8383C20.041 24.8383 24.8678 20.0115 24.8678 14.0573C24.8678 8.10317 20.041 3.27637 14.0868 3.27637ZM1.55762 14.0573C1.55762 7.13763 7.16714 1.52811 14.0868 1.52811C21.0065 1.52811 26.6161 7.13763 26.6161 14.0573C26.6161 20.977 21.0065 26.5866 14.0868 26.5866C7.16714 26.5866 1.55762 20.977 1.55762 14.0573ZM12.0472 11.7263C12.0472 11.2435 12.4386 10.8522 12.9213 10.8522H14.0868C14.5696 10.8522 14.961 11.2435 14.961 11.7263V19.8849C14.961 20.3676 14.5696 20.759 14.0868 20.759C13.6041 20.759 13.2127 20.3676 13.2127 19.8849V12.6004H12.9213C12.4386 12.6004 12.0472 12.2091 12.0472 11.7263Z" fill="#00A19B" />
                                        </svg>
                                        <p style="margin-bottom: 0">Recuerda activar tu tarjeta para <b>compras por internet.</b></p>
                                    </span>

                                    <div class="form__row empty dobble" style="margin-top: 15px">
                                        <div class="form__row__col">
                                            <div class="form__group">
                                                <label class="" for="cardNumber">
                                                    Número de Tarjeta
                                                </label>
                                                <div class="form__group-input">
                                                    <input name="cardNumber" value="1234 1234 1234 1234" type="tel" class="valid">
                                                    <div class="brand"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form__row" style="float: left; width: 50%;">
                                        <div class="form__row__col left">
                                            <div class="form__group">
                                                <label class="" for="cardExp">
                                                    Vencimiento
                                                </label>
                                                <div class="form__group-input">
                                                    <input name="cardExp" placeholder="MM/AAAA" type="tel" class="">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form__row" style="float: left; width: 50%;">
                                        <div class="form__row__col right">
                                            <div class="form__group">
                                                <label class="" for="cardCVV">
                                                    Codigo de seguridad
                                                </label>
                                                <div class="form__group-input">
                                                    <input name="cardCVV" placeholder="CVV" type="tel" class="">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form__row dobble">
                                        <div class="form__row__col">
                                            <div class="form__group">
                                                <label class="" for="select">
                                                    Número de Cuotas
                                                </label>
                                                <div class="form__group__select">
                                                    <select name="select" id="select" disabled="disabled">
                                                        <option value="">
                                                            0
                                                        </option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form__row dobble">
                                        <div class="form__row__col">
                                            <div class="form__group">
                                                <label class="" for="cardEmail">
                                                    Correo Electrónico
                                                </label>
                                                <div class="form__group-input">
                                                    <input name="cardEmail" placeholder="correo@electronico.com" type="email" class="">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form__row dobble">
                                        <div class="form__row__col">
                                            <div class="form__group" style="margin-bottom: 0;">
                                                <button class="btn btn-green opacity" id="palette-right" name="bg">
                                                    Pagar S/ 350.00
                                                </button>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="personalize" id="personalize">
                        <div class="personalize-logotipo">
                            <span class="title">Logotipo</span>
                            <div class="personalize-logotipo__content">
                                <div class="iso-logo">
                                    <div class="iso-logo__item">
                                        <div class="check">
                                            <svg width="9" height="8" viewBox="0 0 9 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M1 3.55361L3.53289 6L8 1" stroke="white" stroke-width="1.4" stroke-linecap="round"></path>
                                            </svg>

                                        </div>
                                        <div class="image">
                                            <img src="https://culqi-static-files.s3.amazonaws.com/v3/v3-checkout/brand.svg" alt="logo">
                                        </div>
                                    </div>
                                    <div class="iso-logo__item">
                                        <div class="check">
                                            <svg width="9" height="8" viewBox="0 0 9 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M1 3.55361L3.53289 6L8 1" stroke="white" stroke-width="1.4" stroke-linecap="round"></path>
                                            </svg>

                                        </div>
                                        <div class="image">
                                            <img src="https://culqi-static-files.s3.amazonaws.com/v3/v3-checkout/brand-culqi.svg" alt="logo">
                                        </div>
                                    </div>
                                    <div class="iso-logo__item">
                                        <div class="errorlogo">
                                            <svg width="7" height="7" viewBox="0 0 7 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M1 1L6 6" stroke="white" stroke-width="1.4" stroke-linecap="round" />
                                                <path d="M6 1L1 6" stroke="white" stroke-width="1.4" stroke-linecap="round" />
                                            </svg>
                                        </div>
                                        <div class="image">
                                            <img src="https://culqi-static-files.s3.amazonaws.com/v3/v3-checkout/bran-culqi-bg.svg" alt="logo">
                                        </div>
                                    </div>

                                </div>
                                <div class="detail-logo">
                                    <li class="detail-logo__list">
                                        <svg width="9" height="8" viewBox="0 0 9 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M1 3.55361L3.53289 6L8 1" stroke="#5BBC43" stroke-width="1.4" stroke-linecap="round"></path>
                                        </svg>

                                        Isotipo
                                    </li>
                                    <li class="detail-logo__list">
                                        <svg width="9" height="8" viewBox="0 0 9 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M1 3.55361L3.53289 6L8 1" stroke="#5BBC43" stroke-width="1.4" stroke-linecap="round"></path>
                                        </svg>

                                        En fondo blanco
                                    </li>
                                    <li class="detail-logo__list">
                                        <svg width="7" height="7" viewBox="0 0 7 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M1 1L6 6" stroke="#D20808" stroke-width="1.4" stroke-linecap="round"></path>
                                            <path d="M6 1L1 6" stroke="#D20808" stroke-width="1.4" stroke-linecap="round"></path>
                                        </svg>

                                        Evita fondos de color
                                    </li>

                                </div>
                            </div>
                        </div>
                        <div class="personalize-url">
                            <span class="title">URL</span>
                            <div class="personalize-url__content">
                                <div class="form__row empty dobble">
                                    <div class="form__row__col">
                                        <div class="form__group" style="margin-bottom: 0;">
                                            <div class="form__group-input">
                                                <input name="url" id="logo-url" placeholder="https://culqi.image.jpg.com" value="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ9anovCoA97NQb66vQtWz2qbH2eRKttKrXg&amp;usqp=CAU" type="url">
                                            </div>
                                            <label id="label-text" for="url">
                                                Copia la URL de tu logotipo
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="personalize-color">
                            <span class="title">Color</span>
                            <div class="personalize-color__content">
                                <p class="paragraph">Personaliza los colores de tu checkout. Elige los colores que más
                                    se acomoden a tu marca.</p>
                                <div class="personalize-color__content-item">
                                    <div class="subtitle">Predeterminado</div>
                                    <div class="color-palette">
                                        <div class="color-palette__item">
                                            <input type="radio" checked="" name="color-palette" class="colorPreviewDefault" id="141414-00a19b">
                                            <label for="141414-00a19b">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(20, 20, 20);"></div>
                                                    <div class="color-container__right" style="background: rgb(0, 161, 155);"></div>
                                                </div>
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <div class="personalize-color__content-item">
                                    <div class="subtitle">Colores clásicos</div>
                                    <div class="color-palette">
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="0E456F-2B88D8">
                                            <label for="0E456F-2B88D8">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(14, 69, 111);"></div>
                                                    <div class="color-container__right" style="background: rgb(43, 136, 216);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="7049A8-9373BF">
                                            <label for="7049A8-9373BF">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(112, 73, 168);"></div>
                                                    <div class="color-container__right" style="background: rgb(147, 115, 191);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="3A6505-85B44C">
                                            <label for="3A6505-85B44C">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(58, 101, 5);"></div>
                                                    <div class="color-container__right" style="background: rgb(133, 180, 76);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="EB6F25-E98B52">
                                            <label for="EB6F25-E98B52">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(235, 111, 37);"></div>
                                                    <div class="color-container__right" style="background: rgb(233, 139, 82);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="0280B5-00B1F5">
                                            <label for="0280B5-00B1F5">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(2, 128, 181);"></div>
                                                    <div class="color-container__right" style="background: rgb(0, 177, 245);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="B40593-D32CB5">
                                            <label for="B40593-D32CB5">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(180, 5, 147);"></div>
                                                    <div class="color-container__right" style="background: rgb(211, 44, 181);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="9C3F10-CA5011">
                                            <label for="9C3F10-CA5011">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(156, 63, 16);"></div>
                                                    <div class="color-container__right" style="background: rgb(202, 80, 17);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="F6911B-FFB600">
                                            <label for="F6911B-FFB600">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(246, 145, 27);"></div>
                                                    <div class="color-container__right" style="background: rgb(255, 182, 0);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="6C0101-9D0606">
                                            <label for="6C0101-9D0606">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(108, 1, 1);"></div>
                                                    <div class="color-container__right" style="background: rgb(157, 6, 6);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="046763-00A19B">
                                            <label for="046763-00A19B">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(4, 103, 99);"></div>
                                                    <div class="color-container__right" style="background: rgb(0, 161, 155);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="63464F-894B5D">
                                            <label for="63464F-894B5D">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(99, 70, 79);"></div>
                                                    <div class="color-container__right" style="background: rgb(137, 75, 93);"></div>
                                                </div>
                                            </label>
                                        </div>
                                        <div class="color-palette__item">
                                            <input type="radio" name="color-palette" id="C50011-E85965">
                                            <label for="C50011-E85965">
                                                <div class="color-container">
                                                    <div class="color-container__left" style="background: rgb(197, 0, 17);"></div>
                                                    <div class="color-container__right" style="background: rgb(232, 89, 101);"></div>
                                                </div>
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <div class="personalize-color__content-item">
                                    <span class="action-visible">
                                        <svg width="9" height="5" viewBox="0 0 9 5" fill="none" class="action-svg" xmlns="http://www.w3.org/2000/svg">
                                            <g clip-path="url(#clip0_478_2514)">
                                                <path d="M1.61794 4.64227L0.913939 3.94377L4.49994 0.357773L8.08594 3.93827L7.38744 4.64227L4.49994 1.75477L1.61794 4.64227Z" fill="#3CB4E5"></path>
                                            </g>
                                            <defs>
                                                <clipPath id="clip0_478_2514">
                                                    <rect width="7.172" height="4.2845" fill="white" transform="translate(8.08594 4.64227) rotate(-180)"></rect>
                                                </clipPath>
                                            </defs>
                                        </svg>
                                        <span class="action-visible-text">Ver más combinaciones</span></span>
                                    <div class="action-container">
                                        <div class="subtitle">Colores complementarios</div>
                                        <div class="color-palette">
                                            <div class="color-palette__item">
                                                <input type="radio" name="color-palette" id="0976C9-F6911B">
                                                <label for="0976C9-F6911B">
                                                    <div class="color-container">
                                                        <div class="color-container__left" style="background: rgb(9, 118, 201);"></div>
                                                        <div class="color-container__right" style="background: rgb(246, 145, 27);"></div>
                                                    </div>
                                                </label>
                                            </div>
                                            <div class="color-palette__item">
                                                <input type="radio" name="color-palette" id="8865B9-F48572">
                                                <label for="8865B9-F48572">
                                                    <div class="color-container">
                                                        <div class="color-container__left" style="background: rgb(136, 101, 185);"></div>
                                                        <div class="color-container__right" style="background: rgb(244, 133, 114);"></div>
                                                    </div>
                                                </label>
                                            </div>
                                            <div class="color-palette__item">
                                                <input type="radio" name="color-palette" id="52463A-00A19B">
                                                <label for="52463A-00A19B">
                                                    <div class="color-container">
                                                        <div class="color-container__left" style="background: rgb(82, 70, 58);"></div>
                                                        <div class="color-container__right" style="background: rgb(0, 161, 155);"></div>
                                                    </div>
                                                </label>
                                            </div>
                                            <div class="color-palette__item">
                                                <input type="radio" name="color-palette" id="EB6F25-00A9A4">
                                                <label for="EB6F25-00A9A4">
                                                    <div class="color-container">
                                                        <div class="color-container__left" style="background: rgb(235, 111, 37);"></div>
                                                        <div class="color-container__right" style="background: rgb(0, 169, 164);"></div>
                                                    </div>
                                                </label>
                                            </div>
                                            <div class="color-palette__item">
                                                <input type="radio" name="color-palette" id="134A29-024064">
                                                <label for="134A29-024064">
                                                    <div class="color-container">
                                                        <div class="color-container__left" style="background: rgb(19, 74, 41);"></div>
                                                        <div class="color-container__right" style="background: rgb(2, 64, 100);"></div>
                                                    </div>
                                                </label>
                                            </div>
                                            <div class="color-palette__item">
                                                <input type="radio" name="color-palette" id="0976C9-D32CB5">
                                                <label for="0976C9-D32CB5">
                                                    <div class="color-container">
                                                        <div class="color-container__left" style="background: rgb(9, 118, 201);"></div>
                                                        <div class="color-container__right" style="background: rgb(211, 44, 181);"></div>
                                                    </div>
                                                </label>
                                            </div>
                                            <div class="color-palette__item">
                                                <input type="radio" name="color-palette" id="CA5011-F6911B">
                                                <label for="CA5011-F6911B">
                                                    <div class="color-container">
                                                        <div class="color-container__left" style="background: rgb(202, 80, 17);"></div>
                                                        <div class="color-container__right" style="background: rgb(246, 145, 27);"></div>
                                                    </div>
                                                </label>
                                            </div>
                                            <div class="color-palette__item">
                                                <input type="radio" name="color-palette" id="141414-D20808">
                                                <label for="141414-D20808">
                                                    <div class="color-container">
                                                        <div class="color-container__left" style="background: rgb(20, 20, 20);"></div>
                                                        <div class="color-container__right" style="background: rgb(210, 8, 8);"></div>
                                                    </div>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- <div class="custom-checkout__footer">
                                            <button class="btn btn-without-line" id="btn-close" type="button">Cancelar</button>
                                            <input class="btn btn-save" id="btn-save" value="Guardar">
                                        </div> -->
        </div>
    </div>
</div>


<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            const setLogoPs = jQuery('input[name="groups[culqi][fields][logo][value]"]').val(); // Al iniciar estará vacío, una vez personalizado el checkout esta variable tendrá seteado el url de logo ingresado
            const setPrimaryColor = ''; // Al iniciar estará vacío, una vez personalizado el checkout esta variable tendrá seteado el color ingresado
            const setSecondaryColor = ''; // Al iniciar estará vacío, una vez personalizado el checkout esta variable tendrá seteado el color ingresado
            const setColors = (setPrimaryColor != '' ? setPrimaryColor.slice(1) : '') + '-' + (setSecondaryColor != '' ? setSecondaryColor.slice(1) : '');
            const setPalette = jQuery('input[name="groups[culqi][fields][theme][value]"]').val();
            console.log('setColors:::', setColors);
            const btnOpen = document.querySelector('#open-modal')
            const overlay = document.querySelector('#overlay')

            const personalize = document.querySelector('#personalize');

            const inputColor = document.getElementsByName('color-palette');
            const paletteLeft = document.querySelector('#palette-left')
            const paletteRight = document.querySelectorAll('#palette-right');
            const action = document.querySelector('.action-visible');
            const actionSvg = document.querySelector('.action-svg');
            const actionContainer = document.querySelector('.action-container');
            const actionTextVisible = document.querySelector('.action-visible-text');
            const inputLogo = document.querySelector('#logo-url');
            const logo = document.querySelector('#logo');
            const labelText = document.querySelector('#label-text');
            let btnClose, btnSave;
            // const btnClose = document.querySelectorAll('.btn-close-checkout-preview')
            // const btnSave = document.querySelector('.btn-save-checkout-preview')

            const logoDefault = logo.src;
            const labelDefault = 'Copia la URL de tu logotipo';


            const actionButton = () => {
                if (isEnabledRadio || isEnabledLogo) {
                    btnSave.disabled = false;
                    btnSave.classList.remove('disabled')
                } else {
                    btnSave.classList.add('disabled')
                    btnSave.disabled = true;
                }
            }

            const getSetColor = () => {
                let color = '';
                if (styleConfig.primaryColor && styleConfig.secondaryColor) {
                    if (styleConfig.primaryColor != '' && styleConfig.secondaryColor != '') {
                        color = styleConfig.primaryColor.slice(1) + '-' + styleConfig.secondaryColor.slice(1);
                    }
                } else if (setPalette != '') {
                    color = setPalette.replace(new RegExp('#', 'g'), '');
                }
                return color;
            }

            const setValidationInput = (input = null, logo = null) => {
                if (typeof input == "boolean") {
                    isEnabledRadio = input
                }
                if (typeof logo == "boolean") {
                    isEnabledLogo = logo
                }
            }

            const configColors = (palette, isRemove) => {
                console.log('setcolors::');
                console.log(palette[0]);
                console.log(palette[1]);
                isRemove = isRemove || false;
                paletteLeft.style.background = isRemove ? null : '#' + palette[0];
                paletteRight.forEach((item) => {
                    switch (item.getAttribute('name')) {
                        case 'color':
                            item.style.color = isRemove ? null : '#' + palette[1];
                            break;
                        case 'svg':
                            item.style.fill = isRemove ? null : '#' + palette[1];
                            break;
                        case 'bg':
                            item.style.background = isRemove ? null : '#' + palette[1];
                            break;
                        default:
                            break;
                    }
                });
            }

            if (setLogoPs != '' && setLogoPs != null && setLogoPs != undefined) {
                inputLogo.src = setColors;
            }

            if (setColors != '' && setColors != null && setColors != undefined) {
                inputColor.forEach(el => {
                    if (el.id == setColors) {
                        el.checked = true
                        configColors(setColors.split('-'))
                    }
                })
            };

            inputColor.forEach(el => {
                const colors = el.id.split('-');
                const lbl = el.nextElementSibling;
                const left = lbl.querySelector('.color-container__left');
                const right = lbl.querySelector('.color-container__right');
                left.style.background = '#' + colors[0];
                right.style.background = '#' + colors[1];
                el.addEventListener('change', e => {
                    const palette = e.target.id.split('-');
                    setValidationInput(isValidUrlLogo ? (e.target.id !== getSetColor()) : false, null)
                    configColors(palette);
                    actionButton();
                })
            })

            inputLogo.addEventListener('input', el => {
                const r = /^(http|https):\/\/[^ "]+$/
                if (r.test(el.target.value)) {
                    let image = new Image();
                    image.src = el.target.value;

                    image.addEventListener('error', () => {
                        setValidationInput(false, false);
                        inputLogo.classList.add('invalid')
                        isValidUrlLogo = false;
                        labelText.style.color = '#D20808';
                        labelText.innerText = checkoutPreviewText.errors.logoInvalid;
                        actionButton();
                    });

                    image.addEventListener('load', () => {
                        if (styleConfig.urlLogo) {
                            if (styleConfig.urlLogo == el.target.value) {
                                setValidationInput(null, false);
                            }
                        } else if (setLogoPs == el.target.value) {
                            setValidationInput(null, false);
                        } else {
                            setValidationInput(true, true);
                        }
                        logo.src = el.target.value;
                        labelText.innerText = checkoutPreviewText.labelDefault;
                        isValidUrlLogo = true;
                        inputLogo.classList.remove('invalid');
                        labelText.removeAttribute('style');
                        actionButton();
                    });
                } else if (el.target.value == '') {
                    labelText.innerText = checkoutPreviewText.labelDefault;
                    inputLogo.classList.remove('invalid');
                    labelText.removeAttribute('style');
                    logo.src = checkoutPreviewText.logoDefault;
                    if (styleConfig.urlLogo) {
                        if (styleConfig.urlLogo == '') {
                            setValidationInput(true, false);
                        } else {
                            setValidationInput(null, true);
                        }
                    } else if (setLogoPs == '') {
                        setValidationInput(true, false);
                    } else {
                        setValidationInput(true, true);
                    }
                    isValidUrlLogo = true;
                    actionButton();
                } else {
                    isValidUrlLogo = false;
                    setValidationInput(false, false);
                    inputLogo.classList.add('invalid')
                    labelText.style.color = '#D20808';
                    labelText.innerText = checkoutPreviewText.errors.logoUrl;
                    actionButton();
                }
            });

            action.addEventListener('click', () => {
                actionSvg.classList.toggle('rotate');
                actionContainer.classList.toggle('active');
                // cambiar texto de un span
                if (actionContainer.classList.contains('active')) {
                    actionTextVisible.innerText = 'Ver menos combinaciones';
                } else {
                    actionTextVisible.innerText = 'Ver más combinaciones';
                }
            });
            let styleConfig = {};
            let isEnabledRadio = false,
                isEnabledLogo = false,
                isValidUrlLogo = true;

            const checkoutPreviewText = {
                labelDefault: 'Copia la URL de tu logotipo',
                logoDefault: 'https://culqi-static-files.s3.amazonaws.com/v3/v3-checkout/brand.svg',
                errors: {
                    logoUrl: 'URL incompleta, falta agregar protocolo https o http',
                    logoInvalid: 'Imagen no válida'
                }
            }
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Personalización',
                buttons: [{
                        text: $.mage.__('Cancelar'),
                        class: 'mymodal1 btn btn-without-line btn-close-checkout-preview',
                        click: function() {
                            if (styleConfig.urlLogo != undefined) {
                                if (styleConfig.urlLogo != '' && styleConfig.urlLogo != null && styleConfig.urlLogo != undefined) {
                                    inputLogo.value = styleConfig.urlLogo;
                                    logo.src = styleConfig.urlLogo;
                                } else {
                                    inputLogo.value = '';
                                    logo.src = checkoutPreviewText.logoDefault;
                                }
                            } else {
                                if (setLogoPs != '' && setLogoPs != null && setLogoPs != undefined) {
                                    inputLogo.value = setLogoPs;
                                    logo.src = setLogoPs;
                                } else {
                                    logo.src = checkoutPreviewText.logoDefault;
                                    inputLogo.value = '';
                                }
                            }
                            labelText.innerText = checkoutPreviewText.labelDefault;
                            inputLogo.classList.remove('invalid');
                            labelText.removeAttribute('style');
                            if (styleConfig.primaryColor && styleConfig.secondaryColor) {
                                document.getElementById(styleConfig.primaryColor.slice(1) + '-' + styleConfig.secondaryColor.slice(1)).click()
                                configColors([styleConfig.primaryColor, styleConfig.secondaryColor]);
                            } else {
                                if (setPalette != '' && setPalette != null && setPalette != undefined) {
                                    document.getElementById(setPalette.replace(new RegExp(/\#/g), '')).click()
                                } else {
                                    configColors(setPalette.split('-'), true);

                                }
                            }
                            setValidationInput(false, false)
                            this.closeModal();
                        }
                    },
                    {
                        text: $.mage.__('Guardar'),
                        class: 'mymodal1 btn btn-save disabled btn-save-checkout-preview',
                        click: function() {

                            const inputs = personalize.getElementsByTagName('input');
                            Array.from(inputs).forEach(e => {
                                if (e.name == 'color-palette') {
                                    if (e.checked) {
                                        const colors = e.id.split('-');
                                        styleConfig.primaryColor = '#' + colors[0];
                                        styleConfig.secondaryColor = '#' + colors[1];
                                    }
                                } else {
                                    styleConfig.urlLogo = e.value;
                                }
                            })
                            //overlay.classList.remove('active');
                            jQuery('input[name="groups[culqi][fields][logo][value]"]').val(styleConfig.urlLogo);
                            jQuery('input[name="groups[culqi][fields][theme][value]"]').val(styleConfig.primaryColor + '-' + styleConfig.secondaryColor);
                            console.log('styleConfig: ', styleConfig)

                            this.closeModal();
                        }
                    }
                ]
            };

            var popup = modal(options, $('#popup-modal'));
            $("#open-modal").on('click', function() {
                btnClose = document.querySelectorAll('.btn-close-checkout-preview')
                btnSave = document.querySelector('.btn-save-checkout-preview')
                setValidationInput(false, false)
                actionButton();
                if (styleConfig.urlLogo != undefined) {
                    if (styleConfig.urlLogo != '' && styleConfig.urlLogo != null && styleConfig.urlLogo != undefined) {
                        inputLogo.value = styleConfig.urlLogo;
                        logo.src = styleConfig.urlLogo;
                    } else {
                        inputLogo.value = '';
                        logo.src = checkoutPreviewText.logoDefault;
                    }
                } else {
                    if (setLogoPs != '' && setLogoPs != null && setLogoPs != undefined) {
                        inputLogo.value = setLogoPs;
                        logo.src = setLogoPs;
                    } else {
                        logo.src = checkoutPreviewText.logoDefault;
                        inputLogo.value = '';
                    }
                }
                if (styleConfig.primaryColor && styleConfig.secondaryColor) {
                    configColors([styleConfig.primaryColor, styleConfig.secondaryColor]);
                } else {
                    if (setPalette != '' && setPalette != null && setPalette != undefined) {
                        configColors(setPalette.replace(new RegExp(/\#/g), "").split('-'));
                    } else {
                        document.querySelector(".colorPreviewDefault").click()
                        configColors(['', ''], true);
                    }
                }
                $("#popup-modal").modal("openModal");
            });

            $(document).ready(function() {

                //$('#payment_us_culqi_timexp').attr('type', 'number');
                //$('#payment_us_culqi_timexp').attr('min', '1');
                //$('#payment_us_culqi_timexp').attr('max', '9999999999');


                jQuery('#' + jQuery('input[name="groups[culqi][fields][theme][value]"]').val().replace('#', '').replace('#', '')).click();
                if (jQuery('input[name="groups[culqi][fields][logo][value]"]').val() != '') {
                    document.querySelector('#logo').src = jQuery('input[name="groups[culqi][fields][logo][value]"]').val();
                }
                jQuery('#logo-url').val(jQuery('input[name="groups[culqi][fields][logo][value]"]').val());
                console.log('beforesetcolors');
                console.log(jQuery('input[name="groups[culqi][fields][theme][value]"]').val());
                if (jQuery('input[name="groups[culqi][fields][theme][value]"]').val() != '') {
                    console.log('readysetcolors');
                    var palettedefault = jQuery('input[name="groups[culqi][fields][theme][value]"]').val().replace('#', '').replace('#', '').split('-');
                    configColors(palettedefault);
                }
            });
        }
    );
</script>